f1=open("read1.txt","r")
f1.seek(0)
print("using read")
print(f1.read())
print('\n')
f1.seek(0)
print("using readline")
print(f1.readline())
print(f1.readline())
print('\n')
f1.seek(0)
print("using readlines")
print(f1.readlines())
f1.close()
